language: rust
os: linux
cache: cargo
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
  - beta
  - stable
env:
  - CARGO_EXTRA_ARGS="--all-features"
  - CARGO_EXTRA_ARGS=""

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean
- cargo build $CARGO_EXTRA_ARGS
- cargo test $CARGO_EXTRA_ARGS

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --exclude-files examples/
  fi
