language: rust
os: linux
cache: cargo
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - nightly
  - beta
  - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean
- cargo build
- cargo test
- cargo test --manifest-path=./fluent-syntax/Cargo.toml --features json

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --exclude-files examples/
  fi
