[package]
name = "fluent-resmgr"
description = """
Resource manager for Fluent localization resources.
"""
version = "0.1.0"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
edition = "2018"
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
fluent-bundle = { path = "../fluent-bundle" }
fluent-locale = "^0.6.0"
unic-langid = "^0.3.0"
fluent-fallback = { path = "../fluent-fallback" }
elsa = "^1.3.2"
